services:

  db:
    image: mysql:8
    restart: no
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: no
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    command: npm run dev
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend_systemet
    restart: no
    ports:
      - "5173:5173"  # Exposing the frontend port
    volumes:
      - ./frontend_systemet:/app
    depends_on:
      - backend

volumes:
  db_data:
