package com.bjorntp.systemet.domain;

import lombok.Data;
import java.time.LocalDateTime;
import java.time.LocalTime;

@Data
public class Product {
  private Long productId;
  private String productNumber;
  private String productNameBold;
  private String productNameThin;
  private String category;
  private String productNumberShort;
  private String producerName;
  private String supplierName;
  private Boolean isKosher;
  private String bottleText;
  private Integer restrictedParcelQuantity;
  private Boolean isOrganic;
  private Boolean isSustainableChoice;
  private Boolean isClimateSmartPackaging;
  private Boolean isEthical;
  private String ethicalLabel;
  private Boolean isWebLaunch;
  private LocalDateTime productLaunchDate;
  private LocalTime sellStartTime;
  private Boolean isCompletelyOutOfStock;
  private Boolean isTemporaryOutOfStock;
  private Double alcoholPercentage;
  private String volumeText;
  private Integer volume;
  private Double price;
  private String country;
  private String originLevel1;
  private String originLevel2;
  private String categoryLevel1;
  private String categoryLevel2;
  private String categoryLevel3;
  private String categoryLevel4;
  private String customCategoryTitle;
  private String assortmentText;
  private String usage;
  private String taste;
  private String[] tasteSymbols;
  private Integer tasteClockGroupBitter;
  private Integer tasteClockGroupSmokiness;
  private Integer tasteClockBitter;
  private Integer tasteClockFruitacid;
  private Integer tasteClockBody;
  private Integer tasteClockRoughness;
  private Integer tasteClockSweetness;
  private Integer tasteClockSmokiness;
  private Integer tasteClockCasque;
  private Double recycleFee;
  private Boolean isManufacturingCountry;
  private Boolean isRegionalRestricted;
  private String packagingLevel1;
  private String packagingCo2ImpactLevel;
  private Boolean isNews;
  private String[] images;
  private Boolean isDiscontinued;
  private Boolean isSupplierTemporaryNotAvailable;
  private Double sugarContent;
  private Double sugarContentGramPer100ml;
  private String seal;
  private String vintage;
  private String[] grapes;
  private String otherSelections;
  private String color;
  private String dishPoints;
  private Boolean isRecommendedByTasteProfile;
  private String hasCasqueTaste;
  private String assortment;
  private Boolean isBsAssortment;
  private Boolean isPaAssortment;
  private Boolean isFsAssortment;
  private Boolean isTsAssortment;
  private Boolean isTseAssortment;
  private Boolean isTsLsAssortment;
  private Boolean isTssAssortment;
  private Boolean isTstAssortment;
  private Boolean isTsvAssortment;
  private Boolean isFsTsAssortment;
}
