-- Camelcase because I did that in the beginning, mistakes where made.

CREATE TABLE products (
    "productId" BIGINT PRIMARY KEY,
    "productNumber" VARCHAR(50),
    "productNameBold" VARCHAR(255),
    "productNameThin" VARCHAR(255),
    "category" VARCHAR(255),
    "productNumberShort" VARCHAR(50),
    "producerName" VARCHAR(255),
    "supplierName" VARCHAR(255),
    "isKosher" BOOLEAN,
    "bottleText" VARCHAR(255),
    "restrictedParcelQuantity" INT,
    "isOrganic" BOOLEAN,
    "isSustainableChoice" BOOLEAN,
    "isClimateSmartPackaging" BOOLEAN,
    "isEthical" BOOLEAN,
    "ethicalLabel" VARCHAR(255),
    "isWebLaunch" BOOLEAN,
    "productLaunchDate" TIMESTAMP,
    "sellStartTime" TIME,
    "isCompletelyOutOfStock" BOOLEAN,
    "isTemporaryOutOfStock" BOOLEAN,
    "alcoholPercentage" NUMERIC(5,2),
    "volumeText" VARCHAR(50),
    "volume" INT,
    "price" NUMERIC(10,2),
    "country" VARCHAR(100),
    "originLevel1" VARCHAR(100),
    "originLevel2" VARCHAR(100),
    "categoryLevel1" VARCHAR(100),
    "categoryLevel2" VARCHAR(100),
    "categoryLevel3" VARCHAR(100),
    "categoryLevel4" VARCHAR(100),
    "customCategoryTitle" VARCHAR(255),
    "assortmentText" VARCHAR(255),
    "usage" TEXT,
    "taste" TEXT,
    "tasteSymbols" TEXT[], -- array for multiple values
    "tasteClockGroupBitter" INT,
    "tasteClockGroupSmokiness" INT,
    "tasteClockBitter" INT,
    "tasteClockFruitacid" INT,
    "tasteClockBody" INT,
    "tasteClockRoughness" INT,
    "tasteClockSweetness" INT,
    "tasteClockSmokiness" INT,
    "tasteClockCasque" INT,
    "recycleFee" NUMERIC(10,2),
    "isManufacturingCountry" BOOLEAN,
    "isRegionalRestricted" BOOLEAN,
    "packagingLevel1" VARCHAR(100),
    "packagingCo2ImpactLevel" VARCHAR(50),
    "isNews" BOOLEAN,
    "images" TEXT[], -- can hold multiple image URLs
    "isDiscontinued" BOOLEAN,
    "isSupplierTemporaryNotAvailable" BOOLEAN,
    "sugarContent" NUMERIC(5,2),
    "sugarContentGramPer100ml" NUMERIC(5,2),
    "seal" VARCHAR(100),
    "vintage" VARCHAR(50),
    "grapes" TEXT[],
    "otherSelections" TEXT,
    "color" TEXT,
    "dishPoints" TEXT,
    "isRecommendedByTasteProfile" BOOLEAN,
    "hasCasqueTaste" VARCHAR(10),
    "assortment" VARCHAR(50),
    "isBsAssortment" BOOLEAN,
    "isPaAssortment" BOOLEAN,
    "isFsAssortment" BOOLEAN,
    "isTsAssortment" BOOLEAN,
    "isTseAssortment" BOOLEAN,
    "isTsLsAssortment" BOOLEAN,
    "isTssAssortment" BOOLEAN,
    "isTstAssortment" BOOLEAN,
    "isTsvAssortment" BOOLEAN,
    "isFsTsAssortment" BOOLEAN,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
